drop schema if exists Hotel cascade ;
CREATE SCHEMA IF NOT EXISTS Hotel;

CREATE TABLE Hotel.types (
                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             type VARCHAR UNIQUE
);

CREATE TABLE Hotel.tenants (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR,
                               surname VARCHAR,
                               phone_number VARCHAR(15) unique,
                               room INTEGER unique
);

CREATE TABLE Hotel.rooms (
                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             type VARCHAR not null ,
                             price INTEGER not null ,
                             footage INTEGER not null ,
                             occupation BOOLEAN DEFAULT FALSE,
                             tenant INTEGER default null,
                             CONSTRAINT tenant_of_room FOREIGN KEY (tenant) REFERENCES Hotel.tenants(id),
                             CONSTRAINT type_of_room FOREIGN KEY (type) REFERENCES Hotel.types(type)
);



INSERT INTO Hotel.types (type) VALUES ('Single'), ('Double'), ('Suite');

INSERT INTO Hotel.tenants (name, surname, phone_number, room) VALUES
                                                                  ('John', 'Doe', '1234567890', 2),
                                                                  ('Jane', 'Smith', '0987654321', 4);

INSERT INTO Hotel.rooms (type, price, footage, occupation, tenant) VALUES
                                                               ('Single', 100, 20, FALSE, null),
                                                               ('Single', 100, 20, TRUE, 1),
                                                               ('Double', 150, 30, FALSE, null),
                                                               ('Double', 150, 30, TRUE, 2),
                                                               ('Suite', 250, 50, FALSE, null);


